name: Grafana Deploy

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

      # Replace with your desired Terraform version something

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-2 --name education-eks-3HJh8Qro

    - name: Install kubectl and kubens
      run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

          curl -LO https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
          chmod +x kubens
          sudo mv kubens /usr/local/bin/

    - name: Install Helm
      run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          sudo ./get_helm.sh
      
  #  - name: Create Namespace
  #    run: kubectl create ns grafana
      
    - name: Clone Grafana
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'Nazarkulova'
        repository: 'Grafana'
    
    - name: Access cloned repo
      run: |
         cd Grafana
         ls -la

    - name: Deploy Helm Chart
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm upgrade my-grafana grafana/grafana -f values.yaml -f values-dev.yaml -n grafana
 
